### ISSUE TITLE
HashMap not updating value when we insert value with same key

### ISSUE THREAD

**Issue by hardikbeladiya** [ClickSimply/typescript-map#2]

**Comment by only-cliches** [comment]
Could you provide some example code that recreates the issue?

**Comment by hardikbeladiya** [comment]
sellOrderMap.sortedSet(1, 2);
            sellOrderMap.sortedSet(1, 3);
            sellOrderMap.sortedSet(1, 5);
            console.log(sellOrderMap.get(1))
it is printing 2 only 

solution is : 
    if (key == this._keys[start]) {
      this._values.splice(start, 0, value);
      return this;
    }
    if (key == this._keys[end]) {
      this._values.splice(end, 0, value);
      return this;
    }
in index.js

**Comment by only-cliches** [comment]
Just pushed v0.0.6, issue should be resolved now.  Let me know if it doesn't work for you. 😃

**Comment by hardikbeladiya** [comment]
Thanks @ClickSimply 👍
