### ISSUE TITLE
Filter not working properly

### ISSUE THREAD

**Issue by boyskila** [ClickSimply/typescript-map#3]
Hi, thanks for the library.
Just found an issue with the filter function in 0.0.6 VERSION. Looks like is related to the key's array which is modified while iterating through it.

Testing with following data:

const tsMap = new TSMap([
            [1, 11],
            [2, 22],
            [3, 33],
            [4, 44],
            [5, 55],
            [6, 66]
        ]);
const result = tsMap.filter(v => v > 50); // should return values [55, 66], instead returned values are [22, 44, 55, 66]

Regards,
Boyko

**Comment by efc** [comment]
I am seeing this issue as well. The result is that filter seems to skip values, it does not even visit them.

**Comment by only-cliches** [comment]
Didn't see this issue a month ago!  Thanks for the PR, it's live on NPM now in version `0.0.7`, this issue should now be resolved.
