### ISSUE TITLE
When sortedSet add an existing key then duplicate values

### ISSUE THREAD

**Issue by daniquir** [ClickSimply/typescript-map#5]
Hi, thanks for yout contribution.

I'm using your lib and I found a strange behaviour.
I have a TSMap on wich I add key/value with sortedSet, the key is stablished and value too, but the value is added with the old value.
The result is a TSMap with a key and two values.
After I delete the existing key and TSMap hasn't any key but has a values.

Thanks, regards.

**Comment by kingsimba** [comment]
This library is useless. See my comments #6

**Comment by only-cliches** [comment]
This has been fixed as of `0.1.0`, thank you for the heads up!
