### ISSUE TITLE
The library has a horrible implementation

### ISSUE THREAD

**Issue by kingsimba** [ClickSimply/typescript-map#6]
1. The implementation uses linear search ``this._keys.indexOf(key)``. The performance is horrible.
2. Why creating another map when TypeScript already have builtin ones?

Anyone reading this, please use builtin type-safe map of TypeScript:
(https://levelup.gitconnected.com/building-type-safe-dictionaries-in-typescript-a072d750cbdf)

```ts
const jiraCustomFields: { [name: string]: string } = {
    location: "customfield_10203",
    userId: "customfield_10204",
    description: "description"
};
```

Or

```ts
const jiraCustomFields: Map<string, string> = new Map([
    ['location ', "customfield_10203"],
    ['userId ', "customfield_10204"],
    ['description ', "description"]
]);
```

Or

```ts
const jiraCustomFields = new class {
    location = "customfield_10203";
    userId = "customfield_10204";
    description = "description";
    [name: string]: string;   // This enables accessing with string, "jiraCustomFields[str]"
}();
```

**Comment by only-cliches** [comment]
1. Yes.  If you want the best performance this isn't the right choice.  Personally, I used this library where the keys where never more than a few hundred so the performance didn't matter.
2. There was no ES5 compatible Map type when this library was written that didn't take hundreds of kilobytes. *Edit: looks like that's still true, if you're targeting ES5 compilation official Typescript maps will not work*.

So if you need an ES5 polyfill it's this library or something like it.

Thanks for your feedback, I might add a note to the library that this isn't a good choice if you plan to store more than a few hundred values in your map.
